AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 99

Rails:
  Enabled: true

Documentation:
  Enabled: false
